# Generated by Django 5.2.4 on 2025-08-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='priority',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated, e.g. python, algorithms', max_length=120),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('topic', models.CharField(help_text='e.g. python, dsa, ml, dbms', max_length=120)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='core.learninggoal')),
            ],
        ),
    ]
