# Generated by Django 5.2.4 on 2025-09-29 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learninggoal_due_date_learninggoal_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learninggoal',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='priority',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
