# Generated by Django 5.2.4 on 2025-11-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_learninggoal_deadline_alter_learninggoal_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggoal',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
